"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = SeedViewerModal;
const jsx_runtime_1 = require("react/jsx-runtime");
function SeedViewerModal({ open, onClose, seed }) {
    if (!open || !seed)
        return null;
    return ((0, jsx_runtime_1.jsx)("div", { style: { position: 'fixed', left: 0, top: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999 }, children: (0, jsx_runtime_1.jsxs)("div", { style: { background: '#fff', padding: 16, maxWidth: 800, width: '90%', maxHeight: '90%', overflow: 'auto', borderRadius: 8 }, role: "dialog", "aria-modal": "true", children: [(0, jsx_runtime_1.jsxs)("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [(0, jsx_runtime_1.jsx)("h3", { style: { margin: 0 }, children: seed.title || seed.name || seed.id }), (0, jsx_runtime_1.jsx)("button", { onClick: onClose, "aria-label": "Close", children: "\u2715" })] }), (0, jsx_runtime_1.jsx)("div", { style: { marginTop: 12 }, children: (0, jsx_runtime_1.jsx)("pre", { style: { whiteSpace: 'pre-wrap', fontFamily: 'inherit' }, children: seed.description || seed.text || JSON.stringify(seed, null, 2) }) }), seed.effects && ((0, jsx_runtime_1.jsxs)("div", { style: { marginTop: 12 }, children: [(0, jsx_runtime_1.jsx)("h4", { children: "Effects" }), (0, jsx_runtime_1.jsx)("ul", { children: seed.effects.map((e, i) => (0, jsx_runtime_1.jsx)("li", { children: typeof e === 'string' ? e : JSON.stringify(e) }, i)) })] })), seed.rewards && ((0, jsx_runtime_1.jsxs)("div", { style: { marginTop: 12 }, children: [(0, jsx_runtime_1.jsx)("h4", { children: "Rewards" }), (0, jsx_runtime_1.jsx)("pre", { style: { whiteSpace: 'pre-wrap', fontFamily: 'inherit' }, children: JSON.stringify(seed.rewards, null, 2) })] })), (0, jsx_runtime_1.jsx)("div", { style: { marginTop: 12, textAlign: 'right' }, children: (0, jsx_runtime_1.jsx)("button", { onClick: onClose, children: "Close" }) })] }) }));
}
