"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.applyFinalStatScaling = exports.getRarityMultiplier = exports.scaleTeachingReward = exports.scaleManualEffects = exports.scaleCultivationSpeed = exports.scalePhysiqueStats = exports.scaleBloodlineStats = exports.getRealmMultiplier = void 0;
const scalingSystem_1 = require("../data/scalingSystem");
Object.defineProperty(exports, "getRealmMultiplier", { enumerable: true, get: function () { return scalingSystem_1.getRealmMultiplier; } });
Object.defineProperty(exports, "scaleBloodlineStats", { enumerable: true, get: function () { return scalingSystem_1.scaleBloodlineStats; } });
Object.defineProperty(exports, "scalePhysiqueStats", { enumerable: true, get: function () { return scalingSystem_1.scalePhysiqueStats; } });
Object.defineProperty(exports, "scaleCultivationSpeed", { enumerable: true, get: function () { return scalingSystem_1.scaleCultivationSpeed; } });
Object.defineProperty(exports, "scaleManualEffects", { enumerable: true, get: function () { return scalingSystem_1.scaleManualEffects; } });
Object.defineProperty(exports, "scaleTeachingReward", { enumerable: true, get: function () { return scalingSystem_1.scaleTeachingReward; } });
Object.defineProperty(exports, "getRarityMultiplier", { enumerable: true, get: function () { return scalingSystem_1.getRarityMultiplier; } });
Object.defineProperty(exports, "applyFinalStatScaling", { enumerable: true, get: function () { return scalingSystem_1.applyFinalStatScaling; } });
