// modalTexts_act6.ts
export const modalTextsAct6: Record<string,string> = {
  act6_cult_founders_seeding: `Founding a domain is not a ceremony; it is the placing of a stone that generations will trip over and bless. The charter requires signatures, resources, and a promise you can't rescind: a claim on land, on people, and on seasons. To proclaim a domain is to accept administration, collection, and defense. You will be called a founder — and founders are remembered in songs and laws alike. Delay keeps options open but delays the solid gains a territory offers: tax, manpower, and a place to bury rivals. Choose the founding now and accept the slow work of governance, or keep your hands clean while others take the risk.`,
  act6_cult_pillar_workshop: `A pillar is a strange kind of metallurgy: part ritual, part smithing, part will. You bring ascend essence and patterns from old tomes; the workshop smells of smoke and memory. If the forge answers, the pillar becomes a focal anchor for a bloodline — a physical object that remembers the family's practice. If it does not, the attempt eats spirit. This is not merely making a tool; it is making a home for an inheritance. The decision is about whether to press a potential now into a fixed thing, or keep it latent and flexible.`,
  act6_cult_heritage_library: `Dust and varnish preserve many things: names, obligations, and instructions for living. The heritage library is where you decide who carries your lessons forward. To name an heir is to put a future in another's hands — to trust someone with the ledger of your life. To scribe a treatise is to leave a method that outlives any single flesh. Both acts are small and enormous at once: small because they are written, enormous because they bind how people will remember and follow you.`,
  act6_cult_domain_rationing: `Rationing is a calculus that reveals your priorities. Feed the armory and you buy security at the cost of contentment; feed the people and loyalty grows while the army waits. Each choice changes what the domain will believe about you. You cannot nourish every thing equally — tradeoffs will be read and remembered. Consider the climate: a people fed is a people that sings your name; an armed people is a people ready for the neighbor that always wants what you have.`,
  act6_cult_tutelage_circle: `A circle of tutelage is the multiplication table of a legacy: teach one, teach many. Opening the circle creates a pulse in the community, accelerating novices into usefulness and creating manuals that bear your imprint. Keeping it private protects secrets and keeps power concentrated. The tutelage circle is a lever: use it to produce a cohort that will serve your aims, or keep mastery close and rare.`,
  act6_cult_ancestral_recall: `Ancestral recall is intimate — you do not call to strangers. You set a bowl of memory and wait for the echo. If the ancestors answer, they hand down a methodology that tastes like home and thunder. If they do not, you feel the cost in the slow bruising of your Dao-Heart. This event is a test of whether your lineage is ready to carry a pillar or whether the call must be postponed until later generations have done their small work.`,

  act6_combat_domain_defense: `The sound of raiders is a borrowed sound — drums and horns in the night that measure what the world wants from you. Leading a defense means exposing yourself as the figure everyone looks toward; delegating means trusting your governors and preserving your body. Either choice writes a line in the domain's ledger: who saved the granaries, who left the walls unmanned. A leader is made of decisions like this, which are neither purely moral nor purely strategic; they are the shape of reputation under stress.`,
  act6_combat_coalition_skirmish: `When coalitions clash the map rewrites itself in a single day. Intervening risks enmeshing your forces in a larger war; exploiting the chaos risks appearing opportunistic but can be decisive if you succeed. The skirmish is an opportunity and a threat: your choice determines whether you are a peacetime steward or a wartime striker. Remember that short-term gains can cost decades in trust.`,
  act6_combat_arena_proving: `The arena does not judge complexity; it judges presence. To step into the ring is to accept a ledger recorded in cheers and jeers, a ledger where your skill is tallied in blood and breath. Victory here translates to a kind of social capital that is both admirably simple and dangerously absolute. Losing is public and memorable; winning is a phrase that will be quoted back to you when you ask favors.`,
  act6_combat_shard_guardian: `Guardians of shards move with logic older than the social orders that now petition them. They sense ownership as a violation; challenging one marks you as someone who reaches with force where others bow with ritual. A shard is a power and a responsibility — claim it and you rewrite the risk map for your rivals. The guardian will test both your cunning and your humility.`,
  act6_combat_assassins_ring: `Hidden blades and whispered promises make a certain architecture of power. Rooting out an assassination ring demonstrates public courage; hiring it reveals a comfort with shadow economies. Both actions alter what deals you can get and how late-night conversations unfold. Choose whether you will govern by visible law or secret leverage.`,
  act6_combat_bastion_siege: `A bastion siege is a test of will and logistics. Committing troops can expand territory, but the cost is measured in the bodies of your people and the endurance of your stores. Withdrawing preserves the seed of your domain but at the price of lost opportunity and public scorn. Sieges mark eras in memory: sometimes they make legends; sometimes they make graves.`,

  act6_politics_crown_assembly: `The assembly is theatre and legal instrument both — a place to set precedent and to bind rulers to new rules. Push autonomy and your domain gains the legal latitude to act independently; centralize and you trade local freedom for the machinery of broader governance. The choice will be cited by future lawyers and sung about by children; it will also determine the flow of taxes and levies that sustain armies and artisans.`,
  act6_politics_heir_accusation: `Scandal is a fungus that spreads if left to rot. Defend your heir and risk exposing old wounds; disinherit and lose the thread of succession but snuff a fire that could consume your house. The move reshapes how families and factions place their bets on you and your line. Decide whether loyalty or pragmatism will be the story you hand the next generation.`,
  act6_politics_coalition_diplomacy: `Diplomacy with coalitions is slow and precise — sometimes a promise and a purse is enough to thin a threat; sometimes a bribe only invites later blackmail. You are negotiating not only with leaders but with their reputations and histories. The wrong bargain can haunt the realm; the right one buys breathing room. Choose a course that fits both your wallet and your conscience.`,
  act6_politics_charter_reform: `Legal reform is the invisible scaffolding of daily life. Changing taxes or succession rules will not be flashy, but decades from now your name may be the reason a farmer keeps his field. Enact reform if you want the steady accrual of advantage; preserve the status quo if you prefer certainty and fewer sparks.`,
  act6_politics_royal_betrayal: `Betrayal by a trusted court hand is corrosive. Expose it and risk tearing the court; cover it and you trade integrity for control. The choice will determine the network of favors and grudges that cradle or strangle your power. Either path leads to a thinner set of friends and enemies — choose which you prefer to sharpen.`,
  act6_politics_grant_royal_banner: `A banner is cloth and claim. Bestowing it binds local rulers and lifts morale; refusing it proclaims independence and invites political friction. The banner is ceremony turned into policy: people rally to symbols. Consider whether you value unity or autonomy more in the ledger of your life.`,

  act6_slice_heir_training: `Heir training is the slow, patient labor that turns names into leaders. Teach governance and you build an administrator for councils; teach martial discipline and you forge a bastion leader. The investment will only pay off later — but when it does, it shifts how secure your house is. Choose the legacy you prefer to hand on: law or sword.`,
  act6_slice_festival_domains: `A festival makes a domain feel like home and attracts traders, diplomats, and spies in equal measure. A grand festival dazzles but invites plots; a modest one calms and steadies. The festival is a mirror held up to your rule: what you celebrate is what you declare about the life you prefer in your lands.`,
  act6_slice_merchant_treaty: `Merchants weave routes and opportunity. Open them and your domain gets regular coin; tax corsairs and you gain shadow income with the inevitable strings. Economies are usually built by small repetitions: every treaty is a brick. Choose whether you will rely on legal markets or the grease of illicit deals.`,
  act6_slice_court_poet: `Poets do strange forms of alchemy: words into memory. Commission a poet to craft the narrative that will surround your reign and, with luck, small phrases will become the scaffolding of legend. Decline and let your life be written by others. Culture is low-cost influence that ages well.`,
  act6_slice_refugee_flow: `When the world breaks, people move. Refugees can be a boon or a burden. Integrate them and your domain gains manpower and new loyalties; expel them and you conserve resources at moral cost. The choice is as practical as it is ethical and it will shape the human fabric of your domain.`,
  act6_slice_secret_chamber: `Hidden chambers are temptations and tests. Explore and you may find a source of rare essence or a trap that marks your flesh and future. Seal it and keep peace at the cost of curiosity. Chambers reward courage and punish overreach — choose how much risk you want to hold.`,

  act6_super_relic_convergence: `Convergence is technical and mystical: the right balance of artifact and essence can birth a shard that changes the land itself. Such shards last and they change the map of advantage in ways that simple armies cannot. Converging consumes precious goods and invites attention; abstaining keeps them as options. This is extreme crafting with systemic consequences.`,
  act6_super_legend_awakening: `Legend awakening is the apex of cultivation and politics: a synthesis of ritual, territory, and lineage. Attempting it forces you to stake material and spiritual capital. Success makes your bloodline a living myth and unlocks abilities whispered of in older books. Failure is painful and public. This is not a gamble for the faint-hearted; it is a wager on eternity.`,
  act6_super_echo_of_emperors: `Echoes of emperors are voices leftover from greater ages. They offer bargains that are both seductive and dangerous: power now in exchange for an obligation later. Accept, and you gain leverage with strings; refuse, and you keep your ledger cleaner. Echoes measure whether you prefer immediate advantage or long-term autonomy.`,
  act6_super_ritual_binding: `Binding is collective work and political theater. It requires allies and craft. Bind a shard to your domain and you anchor a permanent boon — but you also create a beacon that others will covet. Sabotage binding and leave the world more chaotic but less concentrated. The ritual changes both land and story.`,
  act6_super_worldtree_seed: `Planting a worldtree seed is the slowest kind of revolution: it changes the soil, the climate, and with time the whole economy. The seed requires protection and patience but yields lasting bounty and a visible legacy. This act is for rulers who think in generations rather than seasons.`,
  act6_super_great_tribulation24_prep: `This is the last calm before a storm that will reshape legend. Coalition aid brings allies but binds you to promises; sacrificing domain resources is an immediate hedge that costs the living; standing alone is an ethic and a gamble. Your choices now tune the difficulty and the fallout of the coming tribulation. Decide who you owe and what you cannot give.`
};
