export const modalTextsAct7: Record<string,string> = {
  act7_event_1: "The final tribulation approaches. Heaven's wrath descends upon those who dare to transcend mortality.",
  act7_event_2: "Ancient rivals emerge from the shadows, seeking to prevent your ascension to immortality.",
  act7_event_3: "The Heavenly Court takes notice of your cultivation. Their judgment will determine your fate.",
  act7_event_4: "A cosmic rift opens, revealing pathways to realms beyond mortal comprehension.",
  act7_event_5: "Dao debates with immortal sages test the very foundation of your understanding.",
  act7_event_6: "The world trembles as your power reaches heights that threaten the natural order.",
  act7_event_7: "Celestial beings descend to witness your final transformation.",
  act7_event_8: "The fabric of reality bends around your presence as you approach true immortality.",
  act7_event_9: "Ancient prophecies speak of one who would challenge the heavens themselves.",
  act7_event_10: "Your Dao Heart faces its ultimate test as the universe itself opposes your ascension.",
  act7_event_11: "Echoes of past immortals whisper warnings of the price of eternal life.",
  act7_event_12: "The boundary between mortal and divine blurs as your transformation begins.",
  act7_event_13: "Heavenly lightning strikes with the fury of a thousand storms.",
  act7_event_14: "Your mortal shell struggles to contain the immortal essence within.",
  act7_event_15: "The laws of nature bend and break around your ascending form.",
  act7_event_16: "Ancient seals placed by the first immortals begin to crack and crumble.",
  act7_event_17: "Your consciousness expands beyond the confines of a single realm.",
  act7_event_18: "The weight of eternity presses down upon your spirit.",
  act7_event_19: "Celestial armies gather to either welcome or destroy the new immortal.",
  act7_event_20: "Your final choice will echo through the ages, shaping the fate of all cultivation.",
  act7_event_21: "The void between worlds calls to your ascending soul.",
  act7_event_22: "Time itself seems to slow as you approach the threshold of immortality.",
  act7_event_23: "Your mortal memories begin to fade as divine wisdom takes their place.",
  act7_event_24: "The last chains binding you to mortality shatter like glass.",
  act7_event_25: "A new star is born in the heavens, marking your successful ascension.",
  act7_event_26: "The mortal realm grows distant as you take your place among the immortals.",
  act7_event_27: "Your legend becomes myth, inspiring future generations of cultivators.",
  act7_event_28: "The cycle of cultivation begins anew as you transcend mortal understanding.",
  act7_event_29: "Your Dao becomes one with the eternal flow of the universe.",
  act7_event_30: "In achieving immortality, you discover that the journey has only just begun."
};
