"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.XIANXIA_SKILLS = void 0;
exports.XIANXIA_SKILLS = {
    weaponMastery: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'combat',
        description: 'Mastery of various weapons, increasing damage and proficiency.',
        evolution: 'swordQi',
        maxLevel: 10,
    },
    alchemy: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'crafting',
        description: 'Ability to create potions and elixirs for various effects.',
        evolution: 'pillRefining',
        maxLevel: 10,
    },
    comprehension: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'cultivation',
        description: 'Understanding of cultivation techniques and principles.',
        evolution: 'cultivationSpeed',
        maxLevel: 10,
    },
    qiControl: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'cultivation',
        description: 'Control over qi, enhancing cultivation and techniques.',
        evolution: 'qiMastery',
        maxLevel: 10,
    },
    bodyTempering: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'cultivation',
        description: 'Strengthening the body to withstand greater challenges.',
        evolution: 'physicalFortitude',
        maxLevel: 10,
    },
    daoInsight: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'cultivation',
        description: 'Understanding the Dao, enhancing overall cultivation.',
        evolution: 'daoMastery',
        maxLevel: 10,
    },
    combatSkills: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'combat',
        description: 'Skills in hand-to-hand combat and martial arts.',
        evolution: 'martialArtsMastery',
        maxLevel: 10,
    },
    socialSkills: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'social',
        description: 'Ability to interact and influence others effectively.',
        evolution: 'charisma',
        maxLevel: 10,
    },
    mentalFortitude: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'special',
        description: 'Strength of mind, resisting mental attacks and distractions.',
        evolution: 'mentalMastery',
        maxLevel: 10,
    },
    spiritBeastTaming: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'special',
        description: 'Ability to tame and communicate with spirit beasts.',
        evolution: 'spiritBeastMastery',
        maxLevel: 10,
    },
    meditation: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'cultivation',
        description: 'Enhances cultivation speed and mental clarity.',
        evolution: 'deepMeditation',
        maxLevel: 10,
    },
    forging: {
        level: 0,
        exp: 0,
        expToNext: 100,
        category: 'crafting',
        description: 'Ability to forge weapons and items with special properties.',
        evolution: 'masterBlacksmith',
        maxLevel: 10,
    },
};
