/**
 * scripts/merge_equipment.js
 * -------------------------
 * Simple merger for equipment data files under `src/data/`.
 *
 * Output shape (maintainers: keep this file in sync with generated file):
 * - `EQUIPMENT_FULL_META` (named export): the full array of equipment metadata objects.
 *   This preserves all fields (id, name, slot, tier, basePower, description, etc.)
 * - `EQUIPMENT_FULL` (named + default export): an array of equipment id strings used by
 *   legacy callers that expect a simple string list. The default export is preserved
 *   for compatibility.
 *
 * Regeneration: run `node scripts/merge_equipment.js` from the repo root. The script
 * collects `src/data/equipment*.ts`, parses the top-level array literal, normalizes
 * missing fields with safe defaults, deduplicates on `id`, and writes
 * `src/data/equipment_full.ts` with the two exports described above.
 */

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.resolve(__dirname, '..', 'src', 'data');
const OUT_FILE = path.join(DATA_DIR, 'equipment_full.ts');
const OUT_BASENAME = path.basename(OUT_FILE);
const GLOB = /^equipment.*\.ts$/i;

function readFiles() {
  // Exclude the canonical output file from source discovery to avoid
  // including the generated file as an input (which prevents updates from
  // propagating when regenerating).
  return fs.readdirSync(DATA_DIR)
    .filter(f => GLOB.test(f) && f !== OUT_BASENAME)
    .map(f => path.join(DATA_DIR, f));
}

function extractArrayLiteral(content) {
  // Find first '[' after an '=' sign and return the full array literal (including brackets)
  const eq = content.indexOf('=');
  if (eq === -1) return null;
  const start = content.indexOf('[', eq);
  if (start === -1) return null;
  let i = start;
  let depth = 0;
  let inString = false;
  let stringChar = null;
  while (i < content.length) {
    const ch = content[i];
    if (inString) {
      if (ch === '\\') {
        i += 2; // skip escaped
        continue;
      }
      if (ch === stringChar) {
        inString = false;
        stringChar = null;
      }
      i += 1;
      continue;
    }
    if (ch === '"' || ch === "'") {
      inString = true;
      stringChar = ch;
      i += 1;
      continue;
    }
    if (ch === '[') {
      depth += 1;
    } else if (ch === ']') {
      depth -= 1;
      if (depth === 0) {
        return content.substring(start, i + 1);
      }
    }
    i += 1;
  }
  return null;
}

function tryParseArray(arrayText) {
  try {
    const fn = new Function('return ' + arrayText + ';');
    return { ok: true, value: fn() };
  } catch (e) {
    return { ok: false, error: e };
  }
}

function normalize(obj) {
  const out = Object.assign({}, obj);
  if (!out.id) return null;
  if (!out.name) out.name = String(out.id);
  if (!out.slot) out.slot = 'tool';
  if (!out.tier) out.tier = 'F';
  if (typeof out.basePower === 'undefined') out.basePower = 0;
  if (!out.description) out.description = '';
  return out;
}

function main() {
  const files = readFiles();
  console.log('Found data files:', files.map(f => path.relative(process.cwd(), f)).join(', '));
  const map = new Map();
  const errors = [];
  files.forEach(f => {
    const rel = path.relative(process.cwd(), f);
    const src = fs.readFileSync(f, 'utf8');
    const arrayText = extractArrayLiteral(src);
    if (!arrayText) {
      console.log(`  ${rel}: no array literal found`);
      return;
    }
    const parsed = tryParseArray(arrayText);
    if (!parsed.ok) {
      errors.push({ file: rel, reason: 'parse_array', detail: parsed.error.message, snippet: arrayText.slice(0,200) });
      console.log(`  ${rel}: parse error for array literal`);
      return;
    }
    const items = parsed.value;
    console.log(`  ${rel}: parsed ${items.length} item(s)`);
    items.forEach((it, idx) => {
      const norm = normalize(it);
      if (!norm) {
        errors.push({ file: rel, index: idx, reason: 'normalize', snippet: JSON.stringify(it).slice(0,200) });
        return;
      }
      if (map.has(norm.id)) {
        console.warn(`Duplicate id ${norm.id} in ${rel} (skipping duplicate)`);
        return;
      }
      map.set(norm.id, norm);
    });
  });

  if (errors.length) {
    console.error('Errors during parsing/normalization:', errors);
    // Still write partial output but exit non-zero
  }

  const arr = Array.from(map.values());
  const outSource = `// AUTOGENERATED by scripts/merge_equipment.js - do not edit\n// NOTE: exports full metadata as EQUIPMENT_FULL_META and an id-array as default/EQUIPMENT_FULL\nexport const EQUIPMENT_FULL_META = ${JSON.stringify(arr, null, 2)} as const;\n\nexport const EQUIPMENT_FULL = (EQUIPMENT_FULL_META as unknown as any[]).map(x => String(x.id)) as readonly string[];\n\nexport default EQUIPMENT_FULL;\n`;
  fs.writeFileSync(OUT_FILE, outSource, 'utf8');
  console.log(`Wrote ${arr.length} items to ${path.relative(process.cwd(), OUT_FILE)}`);
  if (errors.length) process.exit(2);
}

main();
