"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = BracketView;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const CompetitorCard_1 = __importDefault(require("./CompetitorCard"));
const SmallChip_1 = __importDefault(require("@/components/ui/SmallChip"));
function BracketView({ result, onClose }) {
    const { bracketSize, winnerIndex, rounds, roundsData, participants } = result;
    const [selectedProfile, setSelectedProfile] = (0, react_1.useState)(null);
    return ((0, jsx_runtime_1.jsxs)("div", { style: { border: '1px solid rgba(255,255,255,0.06)', padding: 12, borderRadius: 6, background: 'var(--dark)', maxWidth: 900, overflowX: 'auto' }, children: [(0, jsx_runtime_1.jsxs)("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [(0, jsx_runtime_1.jsx)("div", { style: { fontWeight: 700 }, children: "Tournament Bracket" }), (0, jsx_runtime_1.jsx)("div", { children: onClose && (0, jsx_runtime_1.jsx)("button", { style: { padding: 0 }, onClick: onClose, children: (0, jsx_runtime_1.jsx)(SmallChip_1.default, { children: "Close" }) }) })] }), (0, jsx_runtime_1.jsxs)("div", { style: { marginTop: 8, color: 'var(--muted)' }, children: ["Bracket size: ", bracketSize, " \u2022 Rounds: ", rounds, " \u2022 Winner: ", String(winnerIndex)] }), (0, jsx_runtime_1.jsx)("div", { style: { display: 'flex', gap: 16, marginTop: 12 }, children: (roundsData || []).map((r, ri) => ((0, jsx_runtime_1.jsxs)("div", { style: { minWidth: 180, borderLeft: '1px dashed rgba(255,255,255,0.03)', paddingLeft: 8 }, children: [(0, jsx_runtime_1.jsxs)("div", { style: { fontWeight: 600, marginBottom: 6 }, children: ["Round ", ri + 1] }), (0, jsx_runtime_1.jsx)("div", { style: { display: 'flex', flexDirection: 'column', gap: 8 }, children: r.matches.map((m, mi) => ((0, jsx_runtime_1.jsxs)("div", { style: { padding: 8, borderRadius: 4, background: 'rgba(255,255,255,0.02)', cursor: 'pointer' }, onClick: () => {
                                    // find participant profiles for a/b
                                    const a = (participants || []).find((p) => String(p.id) === String(m.aId));
                                    const b = (participants || []).find((p) => String(p.id) === String(m.bId));
                                    setSelectedProfile({ a: a ? a.profile || a : null, b: b ? b.profile || b : null, match: m });
                                }, children: [(0, jsx_runtime_1.jsxs)("div", { style: { fontSize: '0.9rem' }, children: [String(m.aId), " ", (0, jsx_runtime_1.jsx)("strong", { children: "vs" }), " ", String(m.bId)] }), (0, jsx_runtime_1.jsxs)("div", { style: { fontSize: '0.8rem', color: 'var(--muted)' }, children: ["Winner: ", String(m.winnerId), " \u2022 strength: ", Number(m.aStrength || 0).toFixed(2), "/", Number(m.bStrength || 0).toFixed(2)] })] }, `r${ri}m${mi}`))) })] }, `round-${ri}`))) }), selectedProfile && ((0, jsx_runtime_1.jsxs)("div", { style: { marginTop: 12, padding: 10, borderRadius: 6, background: 'rgba(0,0,0,0.6)', color: 'var(--text)' }, children: [(0, jsx_runtime_1.jsxs)("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [(0, jsx_runtime_1.jsx)("div", { style: { fontWeight: 700 }, children: "Match Details" }), (0, jsx_runtime_1.jsx)("button", { style: { padding: 0 }, onClick: () => setSelectedProfile(null), children: (0, jsx_runtime_1.jsx)(SmallChip_1.default, { children: "Close" }) })] }), (0, jsx_runtime_1.jsxs)("div", { style: { display: 'flex', gap: 12, marginTop: 8 }, children: [(0, jsx_runtime_1.jsx)("div", { style: { minWidth: 260 }, children: (0, jsx_runtime_1.jsx)(CompetitorCard_1.default, { profile: selectedProfile.a, label: "A" }) }), (0, jsx_runtime_1.jsx)("div", { style: { minWidth: 260 }, children: (0, jsx_runtime_1.jsx)(CompetitorCard_1.default, { profile: selectedProfile.b, label: "B" }) })] }), (0, jsx_runtime_1.jsxs)("div", { style: { marginTop: 8, color: 'var(--muted)' }, children: ["Winner: ", String(selectedProfile.match.winnerId)] })] }))] }));
}
