// AUTOGENERATED by scripts/merge_equipment.js - do not edit
// NOTE: exports full metadata as EQUIPMENT_FULL_META and an id-array as default/EQUIPMENT_FULL
export const EQUIPMENT_FULL_META = [
  {
    "id": "arch_spear",
    "name": "Archive Spear",
    "slot": "weapon",
    "tags": [
      "pierce",
      "ethereal"
    ],
    "basePower": 100,
    "tier": "F",
    "description": "A long spear inscribed with archival runes. Designed for precise thrusts that cut through spirit-touched defenses."
  },
  {
    "id": "heavenly_urn",
    "name": "Heavenly Urn",
    "slot": "artifact",
    "tags": [
      "providence_up"
    ],
    "basePower": 10,
    "tier": "F",
    "description": "A small urn said to collect stray providence. It grants modest luck and aids providence-based effects."
  },
  {
    "id": "silk_robe",
    "name": "Silk Robe of Calm",
    "slot": "armor",
    "tags": [
      "calm",
      "resist"
    ],
    "basePower": 10,
    "tier": "F",
    "description": "A lightweight silk robe that soothes the wearer, improving mental resilience and elemental resistance."
  },
  {
    "id": "shadow_cloak",
    "name": "Shadow Cloak",
    "slot": "armor",
    "tags": [
      "stealth",
      "mobility"
    ],
    "basePower": 15,
    "tier": "F",
    "description": "A cloak woven from shadow-silk; it aids stealth and quick movement, blurring the wearer at the edges."
  },
  {
    "id": "mender_ring",
    "name": "Mender Ring",
    "slot": "accessory",
    "tags": [
      "heal",
      "regen"
    ],
    "basePower": 8,
    "tier": "F",
    "description": "A simple ring imbued with slow regenerative energy, helping minor wounds knit over time."
  },
  {
    "id": "forge_hammer",
    "name": "Forge Hammer",
    "slot": "weapon",
    "tags": [
      "forge",
      "artifact"
    ],
    "basePower": 40,
    "tier": "F",
    "description": "A sturdy hammer used by smiths; its strikes fracture alloys and channel tempering qi into crafted goods."
  },
  {
    "id": "beast_whistle",
    "name": "Beast Whistle",
    "slot": "tool",
    "tags": [
      "summon"
    ],
    "basePower": 5,
    "tier": "F",
    "description": "A carved whistle that calls small beasts. It can summon temporary aid from nearby fauna."
  },
  {
    "id": "sky_goggles",
    "name": "Sky Goggles",
    "slot": "accessory",
    "tags": [
      "vision"
    ],
    "basePower": 5,
    "tier": "F",
    "description": "Goggles that enhance distant and aerial vision, letting the wearer read currents and spot flying threats."
  },
  {
    "id": "equip_E_001",
    "name": "Numinous Traveler Boots",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "eraId": "era_3",
    "description": "Stitched with road-song and dust-lore, these boots ease long journeys and fold small distances into a breath. Roadwatchers swear they spare many aches and keep weak paths passable."
  },
  {
    "id": "equip_E_002",
    "name": "Lantern of Quiet Paths",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A lantern that reveals hidden trail-marks and soft compacts left by pilgrims. It guides those who walk lost roads through thin zones of bad luck."
  },
  {
    "id": "equip_E_003",
    "name": "Warden’s Whisper Cloak",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "A thin cloak woven with ward-threads used by border guards; it muffles small alarms and keeps breath small in enemy camps. Useful for scouts and caravan guards alike."
  },
  {
    "id": "equip_E_004",
    "name": "Sealed Pilgrim Satchel",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A satchel with basic seals that protect its contents from mundane damp and curious hands. Merchants and relic-hunters use it to keep small finds intact."
  },
  {
    "id": "equip_E_005",
    "name": "Numinous Eye Pendant",
    "slot": "accessory",
    "tier": "E",
    "basePower": 18,
    "description": "A pendant with a faint silver mote that reveals trivial illusions and false signs. Archivists find it handy when sorting forgeries from true notes."
  },
  {
    "id": "equip_E_006",
    "name": "Folded-Age Satchel",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A satchel lined with old fabric blessed by a Tao School minor rite; small relics keep their edges and faint wards persist. It is common among field researchers of lost Eras."
  },
  {
    "id": "equip_E_007",
    "name": "Stability Bracers",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "Leather bracers inlaid with minor runes to steady the hands and slow tremors. Craftsmen wear them when tempering fragile charms."
  },
  {
    "id": "equip_E_008",
    "name": "Quieter Quill",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A quill used by low-level clerks to copy contracts without disturbing neighbors; notes taken with it have a faint official weight. Scribes keep one in every kit."
  },
  {
    "id": "equip_E_009",
    "name": "Traveler’s Compass",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A compass that favors safe crossings and well-traveled secrets, it does not point true north but to survivable routes. Caravan masters rely on it in bad weather."
  },
  {
    "id": "equip_E_010",
    "name": "Watcher’s Circlet",
    "slot": "head",
    "tier": "E",
    "basePower": 18,
    "description": "A simple circlet that sharpens focus and reduces small distractions; it helps wardens remember patrol routes. It is rarely gifted but often loaned."
  },
  {
    "id": "equip_E_011",
    "name": "Pebble of Return",
    "slot": "artifact",
    "tier": "E",
    "basePower": 18,
    "description": "A small charm carved from river-pebble; when rubbed it slightly strengthens the tie to home and calms wanderlust. Pilgrims carry one when leaving family for a long season."
  },
  {
    "id": "equip_E_012",
    "name": "Tidekeeper Sandals",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "Sandals made for crossing tidal flats and lee shores; they keep feet dry and pace steady. Fisherfolk prize them on uncertain coasts."
  },
  {
    "id": "equip_E_013",
    "name": "Script-Guard Gloves",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "Gloves that protect ink and small wards while handling brittle scrolls; archivists and conservators wear them during delicate work. Their fabric resists seep and scorch."
  },
  {
    "id": "equip_E_014",
    "name": "Minor Conduit Amulet",
    "slot": "accessory",
    "tier": "E",
    "basePower": 18,
    "description": "An amulet that channels small, practical qi for steady hands and clear sight, easing simple rituals. Junior adepts wear it during long practice sessions."
  },
  {
    "id": "equip_E_015",
    "name": "Bound Field Trowel",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A small trowel blessed to reveal shallow relics without disturbing the ground’s deeper wards. Archaeological cells of the Eternal Dao Academy keep one in every kit."
  },
  {
    "id": "equip_F_001",
    "name": "Traveler’s Water Flask",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "eraId": "era_7",
    "description": "A simple flask lined with minor wards that keep water fresh for a few days longer. Common among merchants and patrols."
  },
  {
    "id": "equip_F_002",
    "name": "Scribe’s Wrist-pad",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A padded wrist-rest used by copyists to steady hand and ink; it resists smears and minor ink-blots. Found in most academies."
  },
  {
    "id": "equip_F_003",
    "name": "Iron-Root Buckler",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A small buckler of tempered common metal that protects against knocks and stray blades. Militia and caravan guards carry it for low-risk defense."
  },
  {
    "id": "equip_F_004",
    "name": "Caravan Rope Coil",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A sturdy coil that holds nets and bundles without unravelling; it bears small knots meant to last. Useful for merchants and pack-owners."
  },
  {
    "id": "equip_F_005",
    "name": "Practical Hunter’s Bow",
    "slot": "weapon",
    "tier": "F",
    "basePower": 8,
    "description": "A short bow suited to hunting and small skirmishes; it values reliability over grandeur. Frontier scouts keep one as a dependable tool."
  },
  {
    "id": "equip_F_006",
    "name": "Staple’s Ring",
    "slot": "accessory",
    "tier": "F",
    "basePower": 8,
    "description": "A plain ring blessed with a tiny ward to keep signatures from smudging; mostly used by clerks and minor notaries. It lends faint authority when producing paperwork."
  },
  {
    "id": "equip_F_007",
    "name": "Patchwork Cloak",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A cloak repaired many times and sewn with small charms; it keeps the wearer warm and a little less conspicuous. Often seen on itinerant craftsmen."
  },
  {
    "id": "equip_F_008",
    "name": "Traveler’s Bedroll",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A rolled blanket lined with scent-warding plaits; it keeps nightmares at bay for the overnight watch. Common among caravan hands."
  },
  {
    "id": "equip_F_009",
    "name": "Field-Mender Kit",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A small kit with herbs and salves for treating cuts and minor spiritual abrasions. Millwrights and scouts carry it for minor emergencies."
  },
  {
    "id": "equip_F_010",
    "name": "Courier’s Footwraps",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "Simple footwraps that prevent blisters and steady the step on long routes. Post-runners and messengers favor them."
  },
  {
    "id": "equip_F_011",
    "name": "Stow-Map Scroll",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A foldable map with commonly trodden shortcuts and safe camps marked by caravan guilds. Use it in familiar territory; it will not help beyond known roads."
  },
  {
    "id": "equip_F_012",
    "name": "Mercantile Ledger",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A ledger lined with simple seals that stabilize accounts and discourage petty fraud. Small traders keep one to avoid disputes."
  },
  {
    "id": "equip_F_013",
    "name": "Hearthside Apron",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A practical apron with pockets for tools and small wards for safety in the forge. Artisans wear it when working hot materials."
  },
  {
    "id": "equip_F_014",
    "name": "Guide-Stone Necklace",
    "slot": "accessory",
    "tier": "F",
    "basePower": 8,
    "description": "A carved pebble on a cord that gives faint direction toward local shrines and safe groves. Pilgrims value its small comforts."
  },
  {
    "id": "equip_F_015",
    "name": "Quarterstaff Apprentice",
    "slot": "weapon",
    "tier": "F",
    "basePower": 8,
    "description": "A plain staff favored by novices for training and walking; it is sturdy and well balanced. Many masters begin their apprentices with one."
  },
  {
    "id": "equip_G_001",
    "name": "Loose Nails Dagger",
    "slot": "weapon",
    "tier": "G",
    "basePower": 3,
    "eraId": "era_2",
    "description": "A crude dagger made from scavenged nails; serviceable but blunt. Favored by desperate hands for its availability."
  },
  {
    "id": "equip_G_002",
    "name": "Frayed Cloak",
    "slot": "armor",
    "tier": "G",
    "basePower": 3,
    "description": "A patched cloak with little more than warmth to offer; its charm-work is long faded. It keeps the cold off for a night."
  },
  {
    "id": "equip_G_003",
    "name": "Rusty Lantern",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "An old lantern whose wick is unpredictable and flame small; it still keeps watch in a pinch. Many scavengers carry one for search work."
  },
  {
    "id": "equip_G_004",
    "name": "Worn Belt-Pouch",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A small pouch with a patched seam; it holds loose coins and keeps them out of sight. Useful for petty trade."
  },
  {
    "id": "equip_G_005",
    "name": "Battered Bowl",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A simple bowl dented by years of use; it keeps food and sometimes hides small trinkets. It is humble but durable."
  },
  {
    "id": "equip_G_006",
    "name": "Commoner’s Hoof-Shod Boots",
    "slot": "armor",
    "tier": "G",
    "basePower": 3,
    "description": "Boots with simple metal nails to steady the sole; they protect from thorns and thin ice. Not comfortable, but practical."
  },
  {
    "id": "equip_G_007",
    "name": "Tarnished Copper Brooch",
    "slot": "accessory",
    "tier": "G",
    "basePower": 3,
    "description": "A small brooch once gilded and now dulled; it still fastens a cloak and holds a faint hint of belonging. Often a family heirloom of low rank."
  },
  {
    "id": "equip_G_008",
    "name": "Scavenger’s Hook",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A crude hook used for retrieving small items from rubble and water; simple and effective. Many porters keep one tucked away."
  },
  {
    "id": "equip_G_009",
    "name": "Beggar’s Flute",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A plain flute played for small coins and kinder passersby; it soothes small crowds and calls for alms. Street singers prize its honest tone."
  },
  {
    "id": "equip_G_010",
    "name": "Thin Leather Cap",
    "slot": "head",
    "tier": "G",
    "basePower": 3,
    "description": "A soft cap with little protection beyond keeping hair from the eyes. It is the standard headwear of many rural hands."
  },
  {
    "id": "equip_G_011",
    "name": "Bent Spearhead",
    "slot": "weapon",
    "tier": "G",
    "basePower": 3,
    "description": "A reclaimed spearhead mismatched to its pole; its balance is poor but it will bite in a fight. Frontier folk mend them in times of need."
  },
  {
    "id": "equip_G_012",
    "name": "Weathered Shawl",
    "slot": "armor",
    "tier": "G",
    "basePower": 3,
    "description": "A shawl that smells faintly of smoke and road dust; it hides identity well in crowds. Spies and vagabonds favor its anonymity."
  },
  {
    "id": "equip_G_013",
    "name": "Old Cobbler’s Kit",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A set of basic tools for mending footwear and small leather goods. It is a reliable trade-set for tradespeople."
  },
  {
    "id": "equip_G_014",
    "name": "Hand-Carved Token",
    "slot": "artifact",
    "tier": "G",
    "basePower": 3,
    "description": "A carved token used by small guilds to mark membership; it carries no authority outside its clique. Useful to barter with minor folks."
  },
  {
    "id": "equip_G_015",
    "name": "Patchwork Gauntlet",
    "slot": "armor",
    "tier": "G",
    "basePower": 3,
    "description": "A gauntlet made from layered scraps; it protects the hand from scrapes and small strikes. Blacksmiths and woodcutters wear them for work."
  },
  {
    "id": "equip_H_001",
    "name": "Broken Spoon",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "eraId": "era_9",
    "description": "A spoon with a split handle and a dented bowl; it serves dinner and little else. Still useful where proper utensils are scarce."
  },
  {
    "id": "equip_H_002",
    "name": "Splintered Staff",
    "slot": "weapon",
    "tier": "H",
    "basePower": 1,
    "description": "A staff cracked near the middle and poorly bound; it will hold for a single skirmish if needed. Many novices crack such a staff before they learn control."
  },
  {
    "id": "equip_H_003",
    "name": "Frayed Rope",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A rope with worn fibers and a weak knot; it may bear weight briefly but not for long. Keep a spare if you must climb."
  },
  {
    "id": "equip_H_004",
    "name": "Dull Knife",
    "slot": "weapon",
    "tier": "H",
    "basePower": 1,
    "description": "A kitchen knife that has lost its edge; it will slice bread but not leather. It is better than nothing in a pinch."
  },
  {
    "id": "equip_H_005",
    "name": "Ragged Cloak",
    "slot": "armor",
    "tier": "H",
    "basePower": 1,
    "description": "A ragged scrap that keeps rain from the shoulders for a little while. Street children patch them into longer garments."
  },
  {
    "id": "equip_H_006",
    "name": "Bent Nail Amulet",
    "slot": "accessory",
    "tier": "H",
    "basePower": 1,
    "description": "A bent nail tied to a cord and worn as a talisman by those who have little else. It offers small comfort and superstition."
  },
  {
    "id": "equip_H_007",
    "name": "Cracked Bell",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A bell with a split rim whose ring is thin and short-lived; it still signals a ward or call when needed. Village watch use them for short alarms."
  },
  {
    "id": "equip_H_008",
    "name": "Worn Sandals",
    "slot": "armor",
    "tier": "H",
    "basePower": 1,
    "description": "Sandals with thinned soles that once saw miles; they protect tender feet for a time. Common in poorer districts."
  },
  {
    "id": "equip_H_009",
    "name": "Half-Blank Scroll",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A half-blank piece of scroll used for grocery lists, small notes, or a child’s drawings. It carries no covenant value."
  },
  {
    "id": "equip_H_010",
    "name": "Torn Satchel",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A satchel with a torn strap and a patched seam; it will keep a few coins together but not treasure. Useful only for small errands."
  },
  {
    "id": "equip_H_011",
    "name": "Rust-Scabbed Bracer",
    "slot": "armor",
    "tier": "H",
    "basePower": 1,
    "description": "A bracer with surface rust and weakened threads; it protects poorly and is kept for sentimental value. Old soldiers sometimes keep one as a memory."
  },
  {
    "id": "equip_H_012",
    "name": "Broken Quill",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A quill with a splintered tip that writes like a cough; it is better than nothing when ink must be spilled. Many scribes lose one in odd drawers."
  },
  {
    "id": "equip_H_013",
    "name": "Chip-Cracked Pendant",
    "slot": "accessory",
    "tier": "H",
    "basePower": 1,
    "description": "A pendant whose crystal is cracked but still pretty in a dull way; it holds little power but can be precious to one owner. Mementos often outstrip their worth."
  },
  {
    "id": "equip_H_014",
    "name": "Bent-Hook Harpoon",
    "slot": "weapon",
    "tier": "H",
    "basePower": 1,
    "description": "A harpoon with a bent hook that slips often; it still pulls small catches from shallow waters. Fisherfolk keep spares like this for low-risk days."
  },
  {
    "id": "equip_H_015",
    "name": "Dusty Candle",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A candle whose wick is short and wax brittle; it sheds faint light for a few minutes. Often used in emergency situations when proper light is unavailable."
  },
  {
    "id": "equip_GEN_E_001",
    "name": "Grovewalker Sandals",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "Light sandals braided with forest-bark threads; they steady the step and keep small thorns from claiming a sole. Hunters prefer them for quiet approach."
  },
  {
    "id": "equip_GEN_E_002",
    "name": "Archivist’s Pouch",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A pouch lined with thin protective seals ideal for carrying fragile fragments and inked notes. Junior archivists favor it during digs."
  },
  {
    "id": "equip_GEN_E_003",
    "name": "Dawnglass Locket",
    "slot": "accessory",
    "tier": "E",
    "basePower": 18,
    "description": "A locket of thin glass that dims small illusions and eases the mind’s fog. Pilgrims tuck one inside for the dawn-watch."
  },
  {
    "id": "equip_GEN_E_004",
    "name": "Cartographer’s Folding Rule",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A folding rule inscribed with safe-way marks; it reveals worn paths on maps otherwise blank to the eye. Travelers and scouts use it to avoid old traps."
  },
  {
    "id": "equip_GEN_E_005",
    "name": "Hearth-Glow Shawl",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "A shawl that preserves a little warmth and a little courage; it keeps small wards warm and embers safe. Common in cold trading posts."
  },
  {
    "id": "equip_GEN_E_006",
    "name": "Pilgrim’s Chronicle Band",
    "slot": "accessory",
    "tier": "E",
    "basePower": 18,
    "description": "A braided band that collects small fortunes of memory; it helps the wearer recall camp routes and safe inns. Messengers prize its steadiness."
  },
  {
    "id": "equip_GEN_E_007",
    "name": "City-Guard Spurs",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "Sturdy spurs used by watchmen; they sharpen the step and impose small presence in crowded streets. Used by municipal patrols."
  },
  {
    "id": "equip_GEN_E_008",
    "name": "Minor Forger’s Anvil",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A small anvil used by village smiths with a faint ward for tempering; it steadies heat and reduces spoiled runs. Artisans keep one in every hamlet."
  },
  {
    "id": "equip_GEN_E_009",
    "name": "Tide-Path Token",
    "slot": "artifact",
    "tier": "E",
    "basePower": 18,
    "description": "A token carved with coastal sigils that whispers the time of safe crossing for minor tides. Shorefolk bargain with it for calm passage."
  },
  {
    "id": "equip_GEN_E_010",
    "name": "Scout’s Whisper Band",
    "slot": "accessory",
    "tier": "E",
    "basePower": 18,
    "description": "A thin band that muffles small echoes and keeps footsteps light; scouts wear it on night sorties. It does not hide the brave from gods, only from dogs."
  },
  {
    "id": "equip_GEN_E_011",
    "name": "Ceramist’s Glove",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "A glove tempered to resist kiln heat and to steady fragile shaping; potters who craft relic vessels use it to hold steadier hands."
  },
  {
    "id": "equip_GEN_E_012",
    "name": "Ledger-Warden Pin",
    "slot": "accessory",
    "tier": "E",
    "basePower": 18,
    "description": "A pin that keeps pages closed against drafts and faint cursive tricks; merchants use it to mark ledgers and receipts. It gives small legitimacy to signatures."
  },
  {
    "id": "equip_GEN_E_013",
    "name": "Wayfarer’s Tally-Stone",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A small stone used to mark steps and remember hours on the road; it eases the counting of days on long errands. Pilgrims often gift them for luck."
  },
  {
    "id": "equip_GEN_E_014",
    "name": "Bound-Scroll Wrap",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A wrap that keeps scrolls dry and wards intact during brief rains; clerks and students use it for field notes. It smells faintly of old ink."
  },
  {
    "id": "equip_GEN_E_015",
    "name": "Minor Warded Bracer",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "Bracers carved with simple wards to blunt common hexes; novice adepts strap them on for practice. They are unassuming but useful."
  },
  {
    "id": "equip_GEN_E_016",
    "name": "Harbor-Guide Charm",
    "slot": "artifact",
    "tier": "E",
    "basePower": 18,
    "description": "A small charm that hums when currents are calm and hides the taste of salt. Harbormasters share them with friendly captains."
  },
  {
    "id": "equip_GEN_E_017",
    "name": "Patch-Work Greaves",
    "slot": "armor",
    "tier": "E",
    "basePower": 18,
    "description": "Greaves stitched from stronger scraps and minor wards; they protect shins from knocks and sharp brambles. Common in frontier villages."
  },
  {
    "id": "equip_GEN_E_018",
    "name": "Scribe’s Light Lens",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A small lens that magnifies faded ink and clarifies cramped script; archivists use it to read marginalia in ruined tomes."
  },
  {
    "id": "equip_GEN_E_019",
    "name": "Ferry-Master Rope",
    "slot": "tool",
    "tier": "E",
    "basePower": 18,
    "description": "A rope blessed for river work; it resists rot and keeps knots in place under tide. Ferrymen trust it with lives."
  },
  {
    "id": "equip_GEN_E_020",
    "name": "Waybound Hood",
    "slot": "head",
    "tier": "E",
    "basePower": 18,
    "description": "A hood that shelters the traveler’s face and keeps the chill from piercing the skull; it muffles small prying sorceries. It is practical and discreet."
  },
  {
    "id": "equip_GEN_F_001",
    "name": "Stout Walker’s Boots",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "Solid boots with heavy soles, useful for long walks and bad roads. They return a dependable step to those who cannot afford finer gear."
  },
  {
    "id": "equip_GEN_F_002",
    "name": "Tinker’s Patch Kit",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A small kit with needles and wax for mending cloth and leather at the roadside. Craftsfolk and soldiers carry one."
  },
  {
    "id": "equip_GEN_F_003",
    "name": "Woodcarver’s Apron",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A cloth apron reinforced for splinters and chips; it keeps the hearth worker clean and whole. Simple, but valued."
  },
  {
    "id": "equip_GEN_F_004",
    "name": "Journeyman’s Sling",
    "slot": "weapon",
    "tier": "F",
    "basePower": 8,
    "description": "A sling that delivers small stones with reasonable speed; farmers and shepherds use it to drive off predators."
  },
  {
    "id": "equip_GEN_F_005",
    "name": "Letter-Safe Satchel",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A satchel lined to protect letters and small trinkets from rain; couriers carry it on city runs."
  },
  {
    "id": "equip_GEN_F_006",
    "name": "Cook’s Cleaver",
    "slot": "weapon",
    "tier": "F",
    "basePower": 8,
    "description": "A well-balanced cleaver that serves both kitchen and camp guard; it's simple, sharp enough, and dependable."
  },
  {
    "id": "equip_GEN_F_007",
    "name": "Guild-Token Pendant",
    "slot": "accessory",
    "tier": "F",
    "basePower": 8,
    "description": "A common guild token used to identify membership and to open small doors in a guildhall. It carries modest influence."
  },
  {
    "id": "equip_GEN_F_008",
    "name": "Wood-Splitter Hatchet",
    "slot": "weapon",
    "tier": "F",
    "basePower": 8,
    "description": "A basic hatchet for chopping campwood and for close defense. It serves common folk well enough."
  },
  {
    "id": "equip_GEN_F_009",
    "name": "Field-Priest’s Alms Bowl",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A bowl used for collecting alms and for small rites; it preserves a small amount of ritual cleanliness."
  },
  {
    "id": "equip_GEN_F_010",
    "name": "Merc-Level Cloak",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A cloak of modest cut that shelters from light rain and wind; common among traveling traders."
  },
  {
    "id": "equip_GEN_F_011",
    "name": "Cart-Mender’s Coil",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A coil of rope and spare pins kept for fixing carts on the road; it keeps businesses moving."
  },
  {
    "id": "equip_GEN_F_012",
    "name": "Rookie Quarterstaff",
    "slot": "weapon",
    "tier": "F",
    "basePower": 8,
    "description": "A balanced staff issued for training and walking; used in academies and guild halls for basic drills."
  },
  {
    "id": "equip_GEN_F_013",
    "name": "Commoner’s Wristwrap",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A simple wristwrap that supports the joint and keeps grime out of wounds; it is widespread."
  },
  {
    "id": "equip_GEN_F_014",
    "name": "Postman’s Satchel",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A satchel designed to keep parcels in place and letters neat when traveling between towns."
  },
  {
    "id": "equip_GEN_F_015",
    "name": "Novice’s Inkstone",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A small, reliable inkstone used by apprentices for practice and record-keeping."
  },
  {
    "id": "equip_GEN_F_016",
    "name": "Tavern-Hearth Spoon",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A heavy spoon used in inns for stirring broths and for ladling good cheer; it is sturdy and familiar."
  },
  {
    "id": "equip_GEN_F_017",
    "name": "Guard-Clip Buckle",
    "slot": "accessory",
    "tier": "F",
    "basePower": 8,
    "description": "A practical buckle that secures small equipment and signals service; city watch clip them onto belts."
  },
  {
    "id": "equip_GEN_F_018",
    "name": "Understudy Cloak",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A cloak given to understudies and apprentices to mark station and deflect attention from masters."
  },
  {
    "id": "equip_GEN_F_019",
    "name": "Stable-Hand Bracer",
    "slot": "armor",
    "tier": "F",
    "basePower": 8,
    "description": "A bracer to protect arms from rope burn and hoof kicks; common in stables and farms."
  },
  {
    "id": "equip_GEN_F_020",
    "name": "Lantern-Wick Kit",
    "slot": "tool",
    "tier": "F",
    "basePower": 8,
    "description": "A kit of replacement wicks and seals for common lanterns; useful in long watches."
  },
  {
    "id": "equip_GEN_G_001",
    "name": "Tin-Strip Spoon",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A cheap spoon with a tin rim; basic but usable."
  },
  {
    "id": "equip_GEN_G_002",
    "name": "Frayed Belt",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A belt past its prime; it holds things together for a stretch."
  },
  {
    "id": "equip_GEN_G_003",
    "name": "Worn Cap",
    "slot": "head",
    "tier": "G",
    "basePower": 3,
    "description": "A cap that keeps hair from the eyes and collects a town’s dust."
  },
  {
    "id": "equip_GEN_G_004",
    "name": "Bent-Plate Knife",
    "slot": "weapon",
    "tier": "G",
    "basePower": 3,
    "description": "A poorly straightened knife that will still split rope and peel roots."
  },
  {
    "id": "equip_GEN_G_005",
    "name": "Boxwood Comb",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A simple comb that straightens hair and old knots."
  },
  {
    "id": "equip_GEN_G_006",
    "name": "Rusted Thimble",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A thimble with a rust spot; still helps stitch a seam."
  },
  {
    "id": "equip_GEN_G_007",
    "name": "Dented Kettle",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A kettle with a dent that still boils water well enough."
  },
  {
    "id": "equip_GEN_G_008",
    "name": "Shabby Cloak Pin",
    "slot": "accessory",
    "tier": "G",
    "basePower": 3,
    "description": "A pin to hold a cloak closed; it is ordinary but honest."
  },
  {
    "id": "equip_GEN_G_009",
    "name": "Secondhand Glove",
    "slot": "armor",
    "tier": "G",
    "basePower": 3,
    "description": "A glove with thin padding, good for light work and small injuries."
  },
  {
    "id": "equip_GEN_G_010",
    "name": "Warped Spoon Ladle",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A warped ladle used in crowded kitchens; it serves but splashes."
  },
  {
    "id": "equip_GEN_G_011",
    "name": "Loose-Fit Cap",
    "slot": "head",
    "tier": "G",
    "basePower": 3,
    "description": "A cheap cap that flaps in wind but keeps sun away."
  },
  {
    "id": "equip_GEN_G_012",
    "name": "Torn Satchel Strap",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A strap that has seen better days; it still keeps coins together for short trips."
  },
  {
    "id": "equip_GEN_G_013",
    "name": "Humble Spoon",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A simple eating spoon, serviceable in any modest home."
  },
  {
    "id": "equip_GEN_G_014",
    "name": "Old Cobbler Hammer",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A worn hammer for mending soles and fixing small things."
  },
  {
    "id": "equip_GEN_G_015",
    "name": "Rusty Buckle",
    "slot": "accessory",
    "tier": "G",
    "basePower": 3,
    "description": "A buckle with a bit of rust; it still holds belts closed."
  },
  {
    "id": "equip_GEN_G_016",
    "name": "Cracked Mug",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A mug with a small crack; still good for strong tea."
  },
  {
    "id": "equip_GEN_G_017",
    "name": "Burlap Sack",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A sack that holds grain and odds with modest dignity."
  },
  {
    "id": "equip_GEN_G_018",
    "name": "Bent Spoon",
    "slot": "tool",
    "tier": "G",
    "basePower": 3,
    "description": "A spoon bent in use; a common tool in low markets."
  },
  {
    "id": "equip_GEN_G_019",
    "name": "Mismatched Sock",
    "slot": "armor",
    "tier": "G",
    "basePower": 3,
    "description": "A single, warm sock of dubious pair; it warms a foot in need."
  },
  {
    "id": "equip_GEN_G_020",
    "name": "Patch-Made Glove",
    "slot": "armor",
    "tier": "G",
    "basePower": 3,
    "description": "A glove patched many times that keeps hands safe from thorns."
  },
  {
    "id": "equip_GEN_H_001",
    "name": "Splintered Spoon",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A spoon split down the middle; still usable in emergencies."
  },
  {
    "id": "equip_GEN_H_002",
    "name": "Cracked Pot Lid",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A lid with a chip that fits a pot imperfectly but keeps most steam."
  },
  {
    "id": "equip_GEN_H_003",
    "name": "Stubborn Nail",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A nail that refuses to bend; it does its job once fastened."
  },
  {
    "id": "equip_GEN_H_004",
    "name": "Bent Spoon II",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A bent eating implement; still better than none."
  },
  {
    "id": "equip_GEN_H_005",
    "name": "Cracked Comb",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A comb with a missing tooth, good for coarse hair but not fine grooming."
  },
  {
    "id": "equip_GEN_H_006",
    "name": "Rotted Rope End",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "The end of an old rope, kept as scrap or bandage in a pinch."
  },
  {
    "id": "equip_GEN_H_007",
    "name": "Torn Apron",
    "slot": "armor",
    "tier": "H",
    "basePower": 1,
    "description": "An apron with a torn strap; it protects little but covers modestly."
  },
  {
    "id": "equip_GEN_H_008",
    "name": "Dulled Spoon",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A small, dull spoon that has lost its shine but keeps a kitchen going."
  },
  {
    "id": "equip_GEN_H_009",
    "name": "Faded Ribbon",
    "slot": "accessory",
    "tier": "H",
    "basePower": 1,
    "description": "A ribbon that once bright, now faded; it still ties hair in rough knots."
  },
  {
    "id": "equip_GEN_H_010",
    "name": "Half-Torn Cloth",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A scrap of cloth used for cleaning, bandaging, or stuffing a hole."
  },
  {
    "id": "equip_GEN_H_011",
    "name": "Bent Spoon III",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "Yet another bent spoon, often found at the bottom of common drawers."
  },
  {
    "id": "equip_GEN_H_012",
    "name": "Tattered Note",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A note torn and faded; its ink is mostly gone and its memory thinner still."
  },
  {
    "id": "equip_GEN_H_013",
    "name": "Cracked Trinket",
    "slot": "accessory",
    "tier": "H",
    "basePower": 1,
    "description": "A trinket with a crack; sentimental but not potent."
  },
  {
    "id": "equip_GEN_H_014",
    "name": "Half-Broken Button",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A button missing its mate; keeps a coat shut till the next rain."
  },
  {
    "id": "equip_GEN_H_015",
    "name": "Dented Ladle",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A ladle with a small dent; it still serves broth for the hungry."
  },
  {
    "id": "equip_GEN_H_016",
    "name": "Worn Pebble",
    "slot": "artifact",
    "tier": "H",
    "basePower": 1,
    "description": "A smooth pebble carried for luck by some elders; no magic, but comfort."
  },
  {
    "id": "equip_GEN_H_017",
    "name": "Bent Pin",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A hairpin crooked by long use; it holds, though not elegantly."
  },
  {
    "id": "equip_GEN_H_018",
    "name": "Faded Badge",
    "slot": "accessory",
    "tier": "H",
    "basePower": 1,
    "description": "A badge of office long since retired; it brings memories more than authority."
  },
  {
    "id": "equip_GEN_H_019",
    "name": "Cracked Bead",
    "slot": "accessory",
    "tier": "H",
    "basePower": 1,
    "description": "A bead with a hairline fracture; thread it and keep it anyway."
  },
  {
    "id": "equip_GEN_H_020",
    "name": "Shabby Cloth Wrap",
    "slot": "tool",
    "tier": "H",
    "basePower": 1,
    "description": "A strip of cloth used for wrapping wares; it is cheap, useful, and small."
  }
] as const;

export const EQUIPMENT_FULL = (EQUIPMENT_FULL_META as unknown as any[]).map(x => String(x.id)) as readonly string[];

export default EQUIPMENT_FULL;
